import Head from "next/head";
import formImage from "../public/MSA2.png";
import Image from "next/image";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";

export default function Home() {
  const router = useRouter();

  const formik = useFormik({
    initialValues: {
      comment: "",
      email: "",
      classification: "Bio",
      Media: "نص",
    },

    validationSchema: Yup.object({
      comment: Yup.string()
        //.max(20, "comment must be 20 characters or less.")
        .required("Comment is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
    }),

    onSubmit: (values) => {
      console.log("form submitted");
      console.log(values);
      router.push({ pathname: "/success", query: values });
    },
  });

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full"
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="  h-screen items-center flex justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-1/2 font-latoRegular"
        >
          <div className="flex-1 text-gray-700  p-20">
            <h1 className="text-3xl pb-2 font-latoBold">ذكرى ابو العافية</h1>
            <p className="text-sm  text-gray-500">
            *يرجى تعبئة كل البيانات  للانتقال لصفحة تحميل المحتوى*
            </p>
            <div className="mt-6 ">

              {/* Email input field */}
              <div className="pb-4">
                <label
                  htmlFor="email"
                  className={`block font-latoBold text-lg pb-1 ${
                    formik.touched.email && formik.errors.email
                      ? "text-red-400"
                      : ""
                  }`}
                >
                  {formik.touched.email && formik.errors.email
                    ? formik.errors.email
                    : "Email"}
                </label>

                <p></p>
                <input
                  className="border-2 border-gray-500 p-2 rounded-md w-3/4 focus:border-teal-500 focus:ring-teal-500"
                  type="email"
                  name="email"
                  placeholder="Email address (البريد)"
                  onChange={formik.handleChange}
                  value={formik.values.email}
                  onBlur={formik.handleBlur}
                />
              </div>

              {/* Classification input field */}
              <div className="pb-4">
                <label
                  htmlFor="classification"
                  className="block font-latoBold text-lg pb-1"
                >
                  التصنيف
                </label>
                <select
                  className="border-2 border-gray-500 p-2 rounded-md w-3/4 focus:border-teal-500 focus:ring-teal-500"
                  name="classification"
                  onChange={formik.handleChange}
                  value={formik.values.classification}
                >
                  <option>Bio</option>
                  <option>Political</option>
                  <option>Interest</option>
                  <option>Professional</option>
                </select>
              </div>

              {/* Media input field */}
              <div className="pb-4">
                <label
                  htmlFor="media"
                  className="block font-latoBold text-lg pb-1"
                >
                   نوع الميديا
                </label>
                <select
                  className="border-2 border-gray-500 p-2 rounded-md w-3/4 focus:border-teal-500 focus:ring-teal-500"
                  name="media"
                  onChange={formik.handleChange}
                  value={formik.values.media}
                >
                  <option>نص</option>
                  <option>صورة</option>
                  <option>صوت</option>
                  <option>فيديو</option>
                </select>
              </div>

              {/* Comment input field */}
              <div className="pb-4">
                <label
                  htmlFor="comment"
                  className={`block font-latoBold text-lg pb-1 ${
                    formik.touched.comment && formik.errors.comment
                      ? "text-red-400"
                      : ""
                  } `}
                >
                  {formik.touched.comment && formik.errors.comment
                    ? formik.errors.comment
                    : "التعليق"}
                </label>
                <p className="text-sm font-latoBold text-red-400 "></p>
                <textarea
                  className="border-2 border-gray-500 p-2 rounded-md w-80 h-40 focus:border-teal-500 focus:ring-teal-500 "
                  type="text"
                  name="comment"
                  placeholder="الرجاء إدخال تعليق لوصف المحتوى الذي تم تحميله"
                  onChange={formik.handleChange}
                  value={formik.values.comment}
                  onBlur={formik.handleBlur}
                />
              </div>

              <button
                type="submit"
                className="bg-teal-500 font-latoBold text-lg text-white py-3 mt-6 rounded-lg w-full"
              >
                اضغط للانتقال إلى صفحة إرسال المحتوى
              </button>
            </div>
          </div>
          <div className="relative flex-1">
            <Image
              className=" object-cover rounded-lg"
              fill
              priority
              src={formImage}
              alt="form-learn"
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
